export enum Orbit {
  Elliptical = "ELLIPTICAL",
  Geostationary = "GEOSTATIONARY",
  GeostationaryTransfer = "GEOSTATIONARY_TRANSFER",
  Geosynchronous = "GEOSYNCHRONOUS",
  GeosynchronousTransfer = "GEOSYNCHRONOUS_TRANSFER",
  HeliocentricL1 = "HELIOCENTRIC_L1",
  HeliocentricNA = "HELIOCENTRIC_NA",
  HighEarth = "HIGH_EARTH",
  LowEarth = "LOW_EARTH",
  Lunarflyby = "LUNAR_FLYBY",
  LunarImpactor = "LUNAR_IMPACTOR",
  Lunar = "LUNAR",
  MediumEarth = "MEDIUM_EARTH",
  Polar = "POLAR",
  SolarEscapeTrajectory = "SOLAR_ESCAPE_TRAJECTORY",
  Suborbital = "SUBORBITAL",
  SunEarthL2 = "SUN_EARTH_L2",
  SunSynchronous = "SUN_SYNCHRONOUS",
  SupersynchronousTransfer = "SUPERSYNCHRONOUS_TRANSFER",
  Mars = "MARS",
  Venus = "VENUS",
  Asteroid = "ASTEROID",
  VenusFlyby = "VENUS_FLYBY",
  MarsFlyby = "MARS_FLYBY",
  MercuryFlyby = "MERCURY_FLYBY",
  Unknown = "UNKNOWN",
}
